---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-1270-rebalancing-infra-nodes-openshift-monitoring
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - pvcs
  verbs:
  - delete